### ISSUE TITLE
App flash back after clicking "Export"

### ISSUE THREAD

**Issue by kouhe3** [nfdz/Cryptool#15]

**Comment by nfdz** [comment]
I don't have information about the flash back or crash since there are no analytics tools in the app in order to keep it clean and safe. 
Can you provide me more information? Android version, happens 100% of times, and so on.
Thanks a lot!

**Comment by kouhe3** [comment]
Android 7.1.1
Every time I click "export", it will flash back

**Comment by nfdz** [comment]
I was not able to reproduce your error. However, I did some improvements and now maybe it is working. Check the last release and tell me please.
https://github.com/nfdz/Cryptool/releases/tag/v2.1.2

**Comment by kouhe3** [comment]
Still flash back ..........

**Comment by kouhe3** [comment]
I think the reason for the flash back is that part of the file manager function of my mobile phone system has been deleted. Can you call other file manager to work?

**Comment by nfdz** [comment]
Yes, we are using the standard Android way to interact with File Managers. Not related with Google Apps or Service, it is a AOSP.
Can you provide me more info about the brand of your phone? I will check if we can find a workaround for your brand.

**Comment by kouhe3** [comment]
MY PHONE : 美图T8
Its file manager is integrated into system settings
I think there are other ways to save files (such as sharing files).

**Comment by kouhe3** [comment]
破案了
手机上没有“文件夹管理器”
File Manager .
I don't have the system file manager on my phone .
Your application needs a system file manager to export files. 
That's why the app flashes back. 
F**k 美图，What a user-friendly design.
