### ISSUE TITLE
I can't screenshot this app

### ISSUE THREAD

**Issue by kouhe3** [nfdz/Cryptool#16]
I think we should add an option in the settings to allow screenshots.

**Comment by nfdz** [comment]
This is for security reasons.  The app has this security flag enabled:
`WindowManager.LayoutParams.FLAG_SECURE`

It is a basic but strong feature that can prevents other installed apps taking screenshots without you know it. 

Can you give an example about how would you use the screenshot? 
You have got already copy/paste.

**Comment by kouhe3** [comment]
I want to take a screenshot of what this software looks like when used in order to record tutorial videos.

**Comment by nfdz** [comment]
I understand. I can provide you a **debug** app with the secure flags off. Hope it can help you!
[app-debug.apk.zip](https://github.com/nfdz/Cryptool/files/4439755/app-debug.apk.zip)
