### ISSUE TITLE
Cryptographic Issues

### ISSUE THREAD

**Issue by lynn-stephenson** [nfdz/Cryptool#19]
## Issues

1. The [salt](https://github.com/nfdz/Cryptool/blob/9b258fae1911667e9722ad78ef678114e002b8f9/src/CryptoolApp/app/src/main/java/io/github/nfdz/cryptool/common/utils/CryptographyHelper.kt#L20) is predictable, static, and not sufficiently random.

2. Predictable, static, and non-random [IV](https://github.com/nfdz/Cryptool/blob/9b258fae1911667e9722ad78ef678114e002b8f9/src/CryptoolApp/app/src/main/java/io/github/nfdz/cryptool/common/utils/CryptographyHelper.kt#L21)s cripple the confidentially provided by [AES](https://en.wikipedia.org/wiki/Advanced_Encryption_Standard) in [CBC mode](https://en.wikipedia.org/wiki/Block_cipher_mode_of_operation#Cipher_block_chaining_(CBC)).

3. The current implementation of AES in CBC mode is vulnerable to [padding oracle attacks](https://en.wikipedia.org/wiki/Padding_oracle_attack) due to no authentication, or integrity via a MAC.

4. [PBKDF2](https://en.wikipedia.org/wiki/PBKDF2) with [73 iterations](https://github.com/nfdz/Cryptool/blob/9b258fae1911667e9722ad78ef678114e002b8f9/src/CryptoolApp/app/src/main/java/io/github/nfdz/cryptool/common/utils/CryptographyHelper.kt#L22) is not enough for key derivation from passwords or passphrases.

5. [SHA1](https://en.wikipedia.org/wiki/SHA-1)'s output of 160 bits is not enough for a 256 bit key. The way PBKDF2 works, leads to issues where adversaries may optimize for a faster verification method if you ask PBKDF2 for more than a hash function will output. See [1Password](https://1password.com/)'s [implementation flaws](https://adamcaudill.com/2013/04/16/1password-pbkdf2-and-implementation-flaws/).

## Solutions

1. Use a CPRNG for the salt.

2. Use a CPRNG for the IV.

3. Provide authenticity and integrity via HMAC, with SHA256. [**Encrypt then MAC!**](https://en.wikipedia.org/wiki/Authenticated_encryption#Encrypt-then-MAC)

4. Use 100,000+ iterations for passwords or passphrases. If you are deriving keys from keys, a few iterations is fine.

5. If you are deriving a single 256 bit key, use SHA256 instead of SHA1 with PBKDF2. If you are deriving two 256 bit keys, use SHA512. **Just do not ask PBKDF2 for more bits or bytes than the hash function outputs.**

You should take a look at Moxie's blog post on [cryptographic doom principle](https://moxie.org/blog/the-cryptographic-doom-principle/).

*Consider using [Argon2](https://en.wikipedia.org/wiki/Argon2), or [Scrypt](https://en.wikipedia.org/wiki/Scrypt) in the near future for key derivation instead of PBKDF2. Also consider an AEAD cipher, like [ChaCha20](https://en.wikipedia.org/wiki/Salsa20#ChaCha_variant)-[Poly1305](https://en.wikipedia.org/wiki/Poly1305).*

**Comment by nfdz** [comment]
Thank you very much for the analysis. It's excellent. You are right in all issues. 
When the development of the app started it was more like an experimental and UI testing. We definitely have to fix these points as soon as possible. I hope I can work on it for the next few weeks.

**Comment by lynn-stephenson** [comment]
Sorry, I was wrong *partially* about point 3. Only in certain cases would it be considered vulnerable to padding oracle attacks. You (the oracle) must decrypt a chosen ciphertext and leak padding errors for it to be effective.
