### ISSUE TITLE
Add support for sharing and autogenerate password

### ISSUE THREAD

**Issue by mollyuser** [nfdz/Cryptool#30]
When i am using this app in combination with Whatsapp/Signal/Telegram or so, when i am in the app and i copy the encrypted text i can share it with the apps, but when i am in one of those apps and i recieve encrypted text from my contacts i cannot copy and share it with Cryptool. It would be nice to also share it with the tool so it s mich easier to have a conversation. 

The second thing that would be nice, is to have a small button that auto generates passwords next to the password tile when making a new encrypted conversation. Most people dont know what a safe password is so thos would be a nice addition in my opinion.

**Comment by nfdz** [comment]
Thanks for your proposal @mollyuser, they are great ideas and we will definitely do it for the upcoming version. Stay tuned.

**Comment by nfdz** [comment]
It is live 🎉 
https://github.com/nfdz/Cryptool/releases/tag/3.1.0
https://play.google.com/store/apps/details?id=io.github.nfdz.cryptool

Thanks and keep giving your feedback.

**Comment by mollyuser** [comment]
Thanks a lot for making this possible thos quick. This version of Cryptool is perfect for me. I cant thank u enough.
