### ISSUE TITLE
How to decrypt message in default msg app 

### ISSUE THREAD

**Issue by Gul7333** [nfdz/Cryptool#36]
How to decrypt a message? I sent a message to my friend and he got encrypted message in his default Google msg app .... So how can he decrypt a this message and also whenever he send me a message through crypto graph... It come to my Google messages app... Problem is Crypto has only permission to send message but actually it can't be made default message app.... If you can then plz make an option so that we can make it our default messages app... And decryption and encryption should be automatic for amazing experience with full privacy.... Thanks for your efforts

**Comment by spham** [comment]
Any explaination ? The readme is light
