### ISSUE TITLE
We want to add the search feature in the conversation as well as the key exchange feature 

### ISSUE THREAD

**Issue by Aseel67** [nfdz/Cryptool#38]
I want to add a search in the list of conversations for any text in the conversation, as well as the key exchange feature to facilitate the work of the application and be the best

**Comment by nfdz** [comment]
Hello @Aseel67 
- Let's do the search in the conversations feature, it's a good idea 👍 
- Could you explain your "key exchange feature" idea more, or give an example of a real use case?
Thanks
