### ISSUE TITLE
Encryption/Decryption Functionality Testing:*

### ISSUE THREAD

**Issue by temmytopeqa** [nfdz/Cryptool#40]
Test Scenarios - Test encryption functionality by entering a password and plaintext, then verifying that the ciphertext is generated correctly.
Test Scenario - Test decryption functionality by entering the correct password and ciphertext, then verifying that the plaintext is recovered accurately.

Test Scenario: - Verify that the widget handles incorrect passwords gracefully, displaying an error message or vibrating red X as specified.
Test Scenario:   - Test encryption/decryption with different input lengths and characters to ensure compatibility and accuracy.
Test Scenario: - Verify that encryption/decryption operations work seamlessly in both light and dark themes.

**Comment by BoJackSouthside** [comment]
-----BEGIN PGP MESSAGE-----

0v8AAADXATrCmDyEu++QlE8fqwb6Oi7njXhjpAUwMXIOMRSLr0tb7ZVmybhF1Pp1v5WRPLBVoqnmKnKHr0BhzRzPjSD8iTfzAYzqCmWeEC1Rp6Bpu/cangbNi9sHG7WqeLGCaZfxWxf+UTEuY/youvkrJfcjjQoNGA+cLDAtExzC3x1tALUqISGM0WgvzFALp3KtlaZjLBc4gtDRTG+5LyB07YmRWDelQPUXWnncDDto2D9VHfIkBPJttpJKjYh/9CPpX3s62Y75AqSBZYYMImCpkPmUGx3VeDzxh9g=
=Dqls
-----END PGP MESSAGE-----
