### ISSUE TITLE
Adding Arabic

### ISSUE THREAD

**Issue by Aseel67** [nfdz/Cryptool#54]
I wish the Arabic language was added to the app

**Comment by nfdz** [comment]
Hello @Aseel67, I would like to add Arabic language but I have not the knowledge to translate it properly. I have just added it in [Crowdin](https://crowdin.com/project/cryptool/ar). Please, feel free to help with the translation there, I think you just need to create an account (you can use the Github one).
If you do not like Crowdin, you can do the translation in your Editor locally, like we did [here](https://github.com/nfdz/Cryptool/pull/55).
Thanks!

**Comment by Aseel67** [comment]
I have translated the entire app into Arabic via https://crowdin.com/project/cryptool/ar . Will we see the next release with Arabic added?

**Comment by nfdz** [comment]
Wow! what a great contribution.
Of course, this will be included in the next release `3.2.2`.

**Comment by nfdz** [comment]
https://github.com/nfdz/Cryptool/releases/tag/3.2.2 ✅
